version: "2"
services:
  app:
    build: .
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
    entrypoint: /app/entrypoint.sh
    environment:
      - FLASK_APP=/app/run.py
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xzcv
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
